# Generated by Django 3.2.9 on 2022-01-06 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='countInStock',
            field=models.IntegerField(default=0),
        ),
    ]
