# Generated by Django 3.2 on 2022-01-29 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_orders', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
