# Generated by Django 3.2 on 2022-01-29 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_orders', '0002_auto_20220129_1135'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='razorpay_order_id',
        ),
        migrations.RemoveField(
            model_name='order',
            name='razorpay_payment_id',
        ),
        migrations.RemoveField(
            model_name='order',
            name='razorpay_signature',
        ),
    ]
