# Generated by Django 4.0 on 2022-02-09 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_orders', '0005_alter_phonenumber_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PhoneNumber',
        ),
    ]
