# Generated by Django 4.0 on 2022-02-09 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_orders', '0007_phonenumberfield'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PhoneNumberField',
        ),
    ]
